  version: '3'
  services:
    foldspace-markdown-edit-server:
      build: 
        context: .
        dockerfile: Dockerfile
        args:
        - build_id=${BUILD_ID:-1}
      image: ghcr.io/foldspace-stack/foldspace-markdown-edit-server:latest
      ports:
        - "3010:80"
      environment:
        - BASIC_AUTH_USER=admin
        - BASIC_AUTH_PASSWORD=admin
      volumes:
        - /Users/timger/Github/foldspace/foldspace-stack.github.io/docs/:/app/docs/foldspace-stack/
      restart: unless-stopped